import streamlit as st

def main():
    st.markdown("""
    <div style="
        background-image: linear-gradient(135deg, #BA7517 0%, #D85A30 50%, #993C1D 100%);
        padding: 3px;
        border-radius: 10px;
        text-align: center;
        margin-bottom: 2rem;
    ">
                <h1 style="font-size: 42px; color: white; margin-bottom: 0.5rem;">Discussion and Conclusion</h1>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("## Introduction")
    st.markdown("""
    Extreme heat has become an increasingly important environmental and public health concern worldwide, particularly in tropical countries such as the Philippines. Due to its geographic location near the equator, the Philippines regularly experiences high temperatures, elevated humidity levels, and prolonged exposure to intense solar radiation throughout the year. In recent years, the effects of climate change have further intensified heat conditions, leading to more frequent and severe heat events that affect millions of Filipinos. These conditions pose serious risks to public health, labor productivity, agriculture, transportation, energy consumption, and overall quality of life.
    While actual air temperature is commonly used to describe weather conditions, it does not always accurately represent how hot environmental conditions feel to the human body. Humidity plays a major role in influencing thermal perception because it reduces the efficiency of sweat evaporation, which is the body’s natural cooling mechanism. As humidity increases, the body becomes less effective at releasing heat, causing the perceived or “feels like” temperature to become significantly higher than the actual measured air temperature. For this reason, weather agencies such as PAGASA use heat index measurements to warn the public about dangerous heat conditions.
    Understanding the relationship between temperature, humidity, and perceived heat is especially important in the Philippine context because many Filipinos are exposed to outdoor conditions daily. Construction workers, commuters, farmers, students, delivery riders, and street vendors are among the groups most vulnerable to prolonged heat exposure. Extreme heat may lead to dehydration, heat exhaustion, heat stroke, and worsening of existing medical conditions, particularly among children, elderly individuals, and people with limited access to cooling systems. Consequently, studying heat stress patterns and identifying factors associated with dangerous heat conditions may help communities improve preparedness and reduce health-related risks.
    This study focuses on analyzing weather conditions across selected Philippine cities using exploratory data analysis, statistical hypothesis testing, and machine learning techniques. The research primarily examines the relationship between actual temperature, humidity, and perceived temperature, while also investigating how heat stress varies across time and geographic locations. Through visualizations and statistical methods, the study aims to determine whether humidity significantly amplifies heat stress and whether perceived temperature is a better indicator of dangerous climate conditions than actual air temperature alone.
    In addition to exploratory analysis, the study also applies machine learning techniques to better understand and model heat-related patterns. A forecasting model using Prophet was developed to predict future perceived temperature trends, while a K-Means clustering model was used to group cities according to their heat stress characteristics. These models demonstrate how data science and machine learning can be used to support climate analysis and potentially improve heat advisory systems in the Philippines.
    The study seeks to answer several important research questions: How does humidity influence perceived temperature? When do extreme heat events occur most frequently? How does heat stress differ across Philippine cities? Can machine learning models identify and predict meaningful heat patterns? By addressing these questions, the research aims to provide insights that may help Filipinos better understand environmental heat risks and make more informed decisions regarding health, safety, and daily activities.
    Ultimately, the significance of this study lies in its ability to combine statistical analysis, data visualization, and machine learning to examine a growing climate-related issue in the Philippines. As global temperatures continue to rise, understanding the factors that contribute to dangerous heat conditions becomes increasingly important for public awareness, disaster preparedness, and long-term climate adaptation efforts.
    """)
    
    st.markdown("## Methodology")
    st.markdown("""
    The study followed a data science workflow consisting of data collection, data cleaning, exploratory data analysis, statistical hypothesis testing, and machine learning modeling. Weather data from multiple Philippine cities were gathered, processed, analyzed, and interpreted to better understand the factors influencing heat stress and perceived temperature in the country.
    ### Data Collection
    The dataset used in this study was obtained from Kaggle using the “Philippine Major Cities Weather Data 2025” dataset. The original dataset contained various weather-related variables collected from numerous cities across the Philippines. For the purposes of this study, only the variables relevant to heat stress analysis were retained. These variables included datetime, actual temperature (`main.temp`), humidity (`main.humidity`), perceived temperature (`main.feels_like`), and city name (`city_name`).
    After selecting the relevant variables, the dataset was filtered to include selected cities from Luzon, Visayas, and Mindanao. The inclusion of cities from different regions allowed the study to examine geographic variations in heat stress conditions across the country. The filtered dataset was then exported into a CSV file for further processing and analysis.
    
    ### Data Cleaning and Preprocessing
    Several preprocessing steps were performed to ensure the quality and consistency of the dataset. Missing values were removed to prevent incomplete observations from affecting the statistical analyses and machine learning models. Numerical variables such as temperature, humidity, and perceived temperature were converted into appropriate numeric formats to ensure compatibility with analytical methods.
    The datetime variable was converted into a proper datetime format to enable time-based analysis. Additional variables were also extracted from the datetime column, including the hour of the day and the date. These derived variables allowed the study to analyze temporal heat patterns and identify periods when extreme heat events occur most frequently.
    An “extreme heat” variable was also created to classify observations where the perceived temperature exceeded 38°C. This threshold was selected because temperatures near or above this level are associated with increased risk of heat-related illnesses in tropical environments. Due to the Philippines’ high humidity levels, actual temperatures around 38°C often correspond to dangerous heat index conditions that may negatively affect human health.
    
    ### Exploratory Data Analysis
    Exploratory Data Analysis (EDA) was conducted to understand the distributions, relationships, and patterns present in the dataset. Summary statistics were first generated to describe the central tendencies and variability of the numerical variables. Histograms were used to examine the distributions of actual temperature, humidity, and perceived temperature, while pairplots and scatter plots were used to visualize relationships among variables.
    Several visualizations were specifically designed to address the research questions of the study. Scatter plots were used to analyze the relationship between actual and perceived temperature, while count plots examined the frequency of extreme heat events throughout different hours of the day. Additional visualizations compared heat stress conditions across cities and explored how humidity interacts with temperature to influence perceived heat.
    To evaluate whether the numerical variables followed normal distributions, the Shapiro-Wilk test for normality was applied. Since several variables were found to deviate from normality, non-parametric statistical methods were selected for the hypothesis testing stage of the study.
    
    ### Statistical Hypothesis Testing
    The study performed several statistical tests to evaluate the proposed hypotheses regarding heat stress and perceived temperature.
    The Spearman rank correlation test was used to determine whether humidity significantly influences perceived temperature. This non-parametric test was chosen because it does not require normally distributed variables and is appropriate for measuring monotonic relationships.
    The Wilcoxon signed-rank test was applied to compare actual temperature and perceived temperature measurements. This test evaluated whether perceived temperature is generally greater than actual air temperature under Philippine weather conditions.
    To determine whether perceived temperature is a stronger indicator of extreme heat conditions than actual temperature alone, additional correlation analyses were conducted comparing both variables against identified extreme conditions.
    Lastly, the Kruskal-Wallis test was used to determine whether perceived temperature distributions differ significantly across cities. Since the study involved multiple groups and non-normally distributed data, the Kruskal-Wallis test was selected as an appropriate non-parametric alternative to one-way ANOVA.

    ### Machine Learning Models
    Two machine learning techniques were implemented in the study to further analyze and model heat-related patterns.
    The first model utilized Prophet, a time series forecasting library developed by Meta, to predict future perceived temperature values for selected cities. The model was trained using historical perceived temperature data collected from October to December and was evaluated against actual January observations. Forecast accuracy was assessed using metrics such as Mean Absolute Error (MAE) and Root Mean Squared Error (RMSE).
    The second model applied K-Means clustering to group cities according to their heat stress characteristics. Features used in the clustering process included average actual temperature, average perceived temperature, average humidity, percentage of extreme heat events, and the difference between perceived and actual temperature. Before clustering, the features were standardized to ensure equal scaling among variables. Silhouette scores were computed to evaluate cluster quality and determine an appropriate number of clusters.
    
    ### Tools and Technologies
    The study was implemented using Python and Streamlit. Data preprocessing and analysis were performed using libraries such as Pandas and NumPy, while data visualizations were generated using Matplotlib and Seaborn. Statistical tests were conducted using SciPy, and machine learning models were implemented using Prophet and Scikit-learn. Streamlit was used to create an interactive interface that allows users to explore visualizations, analyses, and forecasting results dynamically.
    Overall, the methodology combined statistical analysis, visualization techniques, and machine learning approaches to investigate heat stress patterns in the Philippines and evaluate how environmental conditions influence perceived temperature and climate-related risk.
    """)

   
    st.markdown("## Discussion")
    
    st.markdown("""
    The results of the exploratory data analysis, hypothesis testing, and machine learning models collectively demonstrate that heat stress in the Philippines is shaped by the interaction of multiple environmental factors, particularly temperature, humidity, time of day, and geographic location. While actual air temperature remains an important indicator of weather conditions, the study consistently shows that perceived or “feels like” temperature provides a more realistic representation of the heat experienced by individuals. This distinction is especially important in tropical countries like the Philippines, where high humidity levels intensify thermal discomfort and reduce the body’s ability to cool itself effectively through evaporation and sweating.
    One of the most significant findings of the study is the strong positive relationship between actual temperature and perceived temperature. The scatter plot comparing these variables revealed that perceived temperature closely follows actual temperature during cooler conditions, but diverges noticeably during hotter periods. As temperatures increase, humidity causes the feels-like temperature to rise faster than the measured air temperature, creating conditions that are substantially more dangerous than what traditional temperature readings may suggest. This observation was further supported by the Spearman correlation test, which found a statistically significant relationship between humidity and perceived temperature. The results indicate that humidity acts as a major amplifier of heat stress and contributes heavily to human discomfort during periods of elevated heat.
    The findings also reinforce the importance of considering perceived temperature rather than relying solely on actual temperature when assessing environmental risk. In tropical climates, moderate temperatures combined with high humidity may produce dangerous heat index conditions capable of causing dehydration, exhaustion, and heat stroke. This highlights why weather agencies such as PAGASA place emphasis on heat index measurements when issuing public heat advisories. The study demonstrates that environmental heat cannot be fully understood through temperature alone because human heat perception is strongly influenced by atmospheric moisture.
    Another important result of the analysis is the clear temporal pattern of extreme heat events. The count plot of extreme heat occurrences showed that dangerous conditions are concentrated during midday and early afternoon hours, particularly between 11 AM and 3 PM. This pattern reflects the natural accumulation of solar radiation throughout the day, causing both temperature and humidity-driven heat stress to intensify as the afternoon approaches. These findings are highly relevant in the Philippine context because many daily activities such as commuting, construction work, farming, outdoor vending, and school activities often occur during these hours.
    The identification of peak heat periods has practical implications for public safety and labor productivity. Outdoor workers and commuters are particularly vulnerable to prolonged heat exposure, which may reduce work efficiency and increase the likelihood of heat-related illnesses. In schools, prolonged exposure to high heat conditions may affect student concentration, physical performance, and overall well-being. Understanding the daily timing of heat stress may therefore help institutions develop adaptive measures such as adjusting work schedules, implementing hydration breaks, rescheduling outdoor activities, or strengthening public heat advisories during high-risk hours.
    The geographic analysis further demonstrated that heat stress conditions vary significantly across Philippine cities. The boxplot visualization revealed clear differences in median perceived temperatures, variability, and frequency of extreme conditions among locations. Certain cities consistently exhibited higher perceived temperatures and wider distributions of heat stress events, while others maintained relatively lower and more stable heat patterns. These differences may be influenced by several factors, including urban density, coastal geography, altitude, vegetation coverage, and localized climatic conditions.
    Urban areas with dense infrastructure and limited green spaces are especially vulnerable to the urban heat island effect, where buildings and paved surfaces absorb and retain heat more efficiently than natural environments. Highly urbanized cities such as Manila, Makati, and Quezon City may therefore experience elevated nighttime temperatures and more intense heat accumulation compared to less urbanized regions. Meanwhile, cities located at higher elevations or near coastal environments may experience more moderate temperatures due to differences in airflow and atmospheric circulation. These findings emphasize that climate adaptation strategies should not be generalized across the country, but instead tailored according to local environmental conditions and vulnerabilities.
    The machine learning models strengthened and expanded the study’s findings by demonstrating that heat-related patterns can be modeled and interpreted computationally. The Prophet forecasting model successfully captured daily perceived temperature trends and produced predictions that aligned closely with actual January observations. Although the forecasting model was trained only on October to December data, it still managed to identify recurring daily heat cycles and periods of elevated heat stress. This suggests that perceived temperature follows predictable behavioral patterns over time, making it possible to develop practical forecasting systems for heat monitoring and public advisories.
    The forecasting model also illustrates how data science techniques may contribute to disaster preparedness and climate adaptation efforts in the Philippines. Predictive models can potentially help citizens anticipate dangerous heat periods and prepare accordingly by adjusting activities, increasing hydration, or avoiding prolonged outdoor exposure. In the future, these systems may be integrated into mobile applications, weather dashboards, or local government advisory systems to provide real-time heat risk assessments for communities.
    Similarly, the K-Means clustering analysis revealed that Philippine cities can be grouped into distinct heat stress profiles based on their average temperature, humidity, and frequency of extreme heat events. The clustering results identified groups of cities with relatively high, moderate, and low heat stress severity. These classifications provide valuable insights into how environmental conditions differ regionally and may help policymakers prioritize climate adaptation strategies in areas that experience more severe heat conditions.
    From a socio-economic perspective, the study highlights the broader consequences of increasing heat stress in the Philippines. Extreme heat affects not only physical comfort but also public health, labor productivity, transportation systems, energy consumption, agriculture, and overall quality of life. Vulnerable populations such as children, the elderly, outdoor workers, and low-income communities face the highest risk because they often have limited access to cooling systems, healthcare resources, or climate-resilient infrastructure.
    In agriculture, prolonged heat exposure may negatively affect crop productivity and livestock conditions, threatening food security and farmer livelihoods. In urban environments, increased use of cooling appliances during extreme heat periods may place additional pressure on electrical infrastructure and contribute to higher household expenses. Heat stress may also disrupt transportation systems and reduce economic productivity by affecting worker performance and increasing health-related absences.
    Despite the significance of these findings, the study has several limitations that should be acknowledged. First, the dataset only covered a limited time period focused mainly on the cooler months of October to January. As a result, the analysis may not fully capture the extreme conditions typically experienced during the Philippine dry season, particularly from March to May when heat indices often reach dangerous levels. A longer dataset covering multiple years and all seasons would likely improve the reliability and representativeness of the results.
    Second, the study relied primarily on weather variables such as temperature, humidity, and perceived temperature. Other potentially important factors including wind speed, rainfall, air pollution, vegetation coverage, urbanization level, and socio-economic conditions were not included in the analysis. Incorporating these variables in future studies may provide a more comprehensive understanding of heat stress and climate vulnerability.
    Lastly, while the machine learning models demonstrated meaningful predictive capabilities, they remain relatively simple prototypes. More advanced methods such as deep learning models, spatiotemporal forecasting systems, or hybrid climate prediction frameworks may improve forecasting accuracy and allow for more detailed localized predictions. Future studies may also incorporate public health data, hospitalization records, or mortality statistics to directly evaluate the real-world impacts of heat stress on Filipino communities.
    Overall, the discussion highlights that heat stress in the Philippines is a multidimensional issue that extends beyond temperature alone. Humidity, geography, urbanization, and time all contribute to dangerous environmental conditions that affect public health and daily life. Through the use of exploratory data analysis, statistical testing, and machine learning, the study demonstrates how data science can provide meaningful insights into climate-related challenges and support more informed decision-making for both citizens and policymakers.
    """)
    
    st.markdown("## Conclusion")
    
    st.markdown("""
    Thus, the study successfully demonstrated that perceived temperature is a more effective and meaningful indicator of heat stress than actual air temperature alone. By analyzing weather data from multiple Philippine cities, the research revealed that humidity significantly amplifies how hot environmental conditions feel to humans, especially during periods of elevated temperature. The results consistently showed strong relationships between humidity, perceived temperature, and extreme heat conditions, supporting all proposed hypotheses.
    The exploratory data analysis identified important patterns in the occurrence of heat stress, particularly the concentration of dangerous heat events during midday and early afternoon hours. Geographic differences among cities also revealed that heat stress is not evenly distributed throughout the Philippines, with some urban areas experiencing significantly higher and more variable perceived temperatures. These findings emphasize the importance of localized climate adaptation strategies rather than relying on uniform nationwide approaches.
    The machine learning models further strengthened the study by showing that heat patterns can be predicted and categorized computationally. The Prophet forecasting model demonstrated that perceived temperature follows predictable daily trends, while the K-Means clustering model identified distinct city heat stress profiles based on environmental conditions. Together, these models highlight the potential of data science and machine learning in improving climate monitoring, forecasting, and public awareness systems in the Philippines.
    The significance of this study extends beyond academic research because heat stress has direct consequences on public health, labor productivity, transportation, agriculture, and overall quality of life. As climate change continues to intensify global temperatures, Filipinos will likely face more frequent and severe heat-related risks in the coming years. Understanding the environmental factors that contribute to dangerous heat conditions is therefore essential for improving preparedness, resilience, and community safety.
    Based on the findings, several practical recommendations may be provided for Filipino citizens and local communities. Individuals should monitor perceived temperature or heat index values instead of relying solely on actual temperature readings, particularly during the hottest hours of the day. Limiting outdoor activities during midday periods, staying hydrated, wearing light clothing, and seeking shaded or ventilated areas may significantly reduce the risk of heat-related illnesses. Schools, workplaces, and local government units may also use heat-related data to improve scheduling decisions, strengthen public advisories, and implement localized heat adaptation measures.
    Ultimately, the study demonstrates that combining statistical analysis, visualization, and machine learning provides valuable insights into climate-related challenges in the Philippines. By understanding how heat stress develops and affects different communities, Filipinos can make more informed decisions that improve health, safety, preparedness, and resilience in an increasingly warming environment.
    """)
   
